spring:
  application:
    name: utile-be-gateway
  cloud:
    gateway:
      routes:
        - id: utile-service
          uri: http://localhost:8083
          predicates:
            - Path=/users/**
        - id: professional-service
          uri: http://localhost:8084
          predicates:
            - Path=/professionals/**


springdoc:
  swagger-ui:
    show-extensions: true
    show-common-extensions: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8081
